@host = http://localhost:8080

GET {{host}}/health
###
GET {{host}}/api/spaceships
###
POST {{host}}/api/spaceships
Content-Type: application/json

{"name":"Odyssey","class":"Research","crew":24}
###
DELETE {{host}}/api/spaceships/1

